#!/bin/sh

# User specific aliases and functions
alias ls='ls -F --color=auto'
alias ll='ls -lhF --color=auto'
alias la='ls -lahF --color=auto'
alias grep='grep --color=auto'
alias ggrep='grep -n --exclude={\*.o,\*.pem,\*.pdf,\*.swn,\*.swo,\*.swp,tags,cscope.out} --exclude-dir=.ccls-cache --color=auto'
alias mkdir='mkdir -p'
alias vi='vim'

alias mux='tmuxinator'

alias gdb='gdb -q'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Mistakes
alias gti='git'
alias dc='cd'

# Config files
alias cfg-sxhkd='vim ~/.config/sxhkd/sxhkdrc'
alias cfg-bspwm='vim ~/.config/bspwm/bspwmrc'
alias cfg-polybar='vim ~/.config/polybar/config'
alias cfg-rofi='vim ~/.config/rofi/config.rasi'
alias cfg-conky='vim ~/.config/conky'
alias cfg-alacritty='vim ~/.config/alacritty/alacritty.yml'
alias cfg-picom='vim ~/.config/picom/picom.conf'

[[ -f "$HOME/.aliases.local" ]] && source "$HOME/.aliases.local"
