#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"
export EDITOR=vim
export PAGER=less
export LESS=-Ri
export CSCOPE_EDITOR=/usr/bin/vim
export PYTHONSTARTUP=~/.python/pythonrc.py

# Declare vim tmp dir so that they can be overwritten in local zshrc
export VIM_TMP_DIR="$HOME/.vim/tmp"
export VIM_SWP_DIR="$VIM_TMP_DIR/swpdir"
export VIM_UNDO_DIR="$VIM_TMP_DIR/undodir"

[[ -f "$HOME/.exports.local" ]] && source "$HOME/.exports.local"
