#!/bin/sh

CAPTURE_TMP_FILE=/tmp/last
PROMPT_RE="\[$(hostname)\]"

capture_tmux () {
	local tmp=$(mktemp)
	tmux capture-pane -epS -10000 > $tmp
	tac $tmp | sed "0,/$PROMPT_RE/d;/$PROMPT_RE/q" | tac > $CAPTURE_TMP_FILE
	rm -f $tmp
}

lesslast() {
	capture_tmux
	less $CAPTURE_TMP_FILE
}

vilast() {
	capture_tmux
	vi $CAPTURE_TMP_FILE
}

rgl() {
	rg -g "!cscope*" -g "!tags" "$@" --color=always --heading -n | less -R
}
