#!/bin/bash

numlockx &
setxkbmap -option caps:escape
picom &

external_monitor=$(xrandr --query | grep 'DP-1')
if [[ $external_monitor == *connected* ]]; then
	xrandr --output eDP-1 --primary --output DP-1 --above eDP-1
fi

xrdb $HOME/.Xresources
xset +fp $HOME/.local/share/fonts
xset fp rehash
xsetroot -cursor_name left_ptr

xset s 600 5
if [[ -f /usr/lib/xsecurelock/dimmer ]]; then
	xss-lock -n /urs/lib/xsecurelock/dimmer -l -- xsecurelock &
elif [[ -f /usr/local/libexec/xsecurelock/dimmer ]]; then
	xss-lock -n /urs/local/libexec/xsecurelock/dimmer -l -- xsecurelock &
fi

feh --bg-scale $HOME/Pictures/wallpaper.jpg

exec bspwm
